### ISSUE TITLE
For hacktoberfest. Create a Twitter bot 

### ISSUE THREAD

**Issue by Attupatil** [Attupatil/Tweeter_bot_autoliker-retweeter#1]
Create a twitter bot

**Comment by kamil200** [comment]
i would like work on this feature

**Comment by Attupatil** [comment]
> i would like work on this feature

Sure @kamil200 go for it..make new implementation for the previous code or make documentation
Love opensource love hacktoberfest

**Comment by yashqwerty1** [comment]
Can U assign me this work I created one already.

**Comment by Attupatil** [comment]
> Can U assign me this work I created one already.

You can create a seperate folder
